### PR TITLE
Queue

### LINKED ISSUE #34: Replace failed_logs table with Laravel queues and use handling for retrying failed jobs
Instead of using our custom `failed_logs` table, replace this with Laravel queues and utilize their handling for retrying failed jobs. 

Rogue will be responsible for knowing about failed requests to Phoenix and then also retrying failed jobs.

### PR DESCRIPTION
**Pull request by chloealee**
#### What's this PR do?
- Refactors to use Laravel queues and error handling.
- Updates test to mock the job that sends reporback from Rogue->Phoenix instead of the Phoenix class.
- Drops the `failed_logs` table.
- Adds the `failed_jobs` table. 

#### How should this be reviewed?
- Make sure the tests are passing by running `phpunit` in the vagrant box.
- To manually test:
  - Log into your local. 
  - Sign up for a campaign. 
  - Go to your "My Account" page. 
  - See that you are signed up for that campaign.
  - Post reportback via postman for that campaign and campaign run, with your `drupal_id`. 
  - Refresh your "My Account" page and make sure the campaign has been moved from "YOU'RE DOING" to "YOU DID"
  Example Postman request:
screen shot 2016-09-12 at 3 06 15 pm

#### Any background context you want to provide?
Question -  @sbsmith86 when we are updating the reportback, do we want to dispatch the job to send this to Phoenix as well?

Note from Shae for future planning: 
Shae Smith [11:27 AM]  
I don’t know if this is needed at the moment, but we could also use the event system in laravel to send stuff to queues since we might want a way of notifiying a bunch of systems that something happened in rogue. but I think this approach is fine for now.
https://dosomething.slack.com/archives/rogue/p1473348457000138

#### Relevant tickets
Fixes #34 

#### Checklist
- [ ] Documentation added for new features/changed endpoints.
- [ ] Tested on staging.
- [ ] Pinged a PM if this is a larger PR that would benefit from some additional testing love.

### CODE REVIEW

**Comment by sbsmith86** [comment]
@chloealee it depends on how #6972 is implemented. If you save the update to drupal first and then send it to rogue then we don't need to send it back. And, I sorta feel like that flow is ok for now, since we don't want to add more work to this project.

**Comment by chloealee** [comment]
@sbsmith86 cool, makes sense!

**Comment by sbsmith86** [comment]
The code looks fine to me, also.

**Comment by chloealee** [comment]
Great! Can I 🚢 ?

**Comment by sbsmith86** [comment]
sure!

File: app/Services/ReportbackService.php [hunk 1]
```diff
@@ -14,14 +14,14 @@ class ReportbackService
...
      */
-    protected $phoenix;
+    protected $sendReportbackToPhoenix;
 
-    public function __construct(ReportbackRepository $reportbackRepository, Phoenix $phoenix)
+    public function __construct(ReportbackRepository $reportbackRepository, SendReportbackToPhoenix $sendReportbackToPhoenix)
     {
         $this->reportbackRepository = $reportbackRepository;
-        $this->phoenix = $phoenix;
+        $this->sendReportbackToPhoenix = $sendReportbackToPhoenix;
```
Comment (DFurnes) [inline app/Services/ReportbackService.php]: Just got around to looking at this now, so sorry to comment after merge. 😁 It looks like this injected class and property aren't used anywhere? Dispatching by creating a new instance inline (like you did below) is pretty standard convention so this should be safe to remove.

File: app/Jobs/SendReportbackToPhoenix.php [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+    }
+
+    /**
+     * Execute the job.
+     *
+     * @return void
+     */
+    public function handle()
+    {
+        $phoenix = new Phoenix;
```
Comment (DFurnes) [inline app/Jobs/SendReportbackToPhoenix.php]: Definitely not necessary, but it may be cleaner to use the `$this->phoenix` that you created above rather than instantiating a second client as a local variable (or just remove the property above!).

File: app/Services/ReportbackService.php (hunk 1 above)
Comment (chloealee) [inline app/Services/ReportbackService.php]: ah shoot yes, I forgot to delete that, thanks @DFurnes ! I'll make the changes and submit a new PR!
